services:
  jdc-redis:
    image: redis:7-alpine
    container_name: jdc-redis
    command: redis-server --requirepass "password"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "password", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  redis_data:
